services:
  backend:
    build:
      context: ./rest-modules
      dockerfile: Dockerfile
    container_name: rest-modules-dev
    ports:
      - "3001:3001"
      - "9229:9229"
    command: npm run start:debug
    volumes:
      - ./rest-modules:/app
      - rest_node_modules:/app/node_modules # Evita que los node_modules locales sobreescriban los del contenedor
    environment:
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
      - TSC_WATCHFILE=DynamicPriorityPolling
      - WATCHPACK_POLLING=true
      - DATABASE_URL=postgresql://neondb_owner:npg_SRCfydYv8lT7@ep-restless-field-apo093l8.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
    networks:
      - dev-network

  frontend:
    build:
      context: ./AstroDeLaConchaSuMar
      dockerfile: Dockerfile
    container_name: astro-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./AstroDeLaConchaSuMar:/app
      - astro_node_modules:/app/node_modules # Evita conflictos de dependencias entre SO
    environment:
      - PORT=3000
      - BACKEND_URL=http://backend:3001
      - PUBLIC_BACKEND_URL=http://127.0.0.1:3001
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
      - WATCHPACK_POLLING=true
    networks:
      - dev-network
    depends_on:
      - backend

networks:
  dev-network:
    driver: bridge

volumes:
  rest_node_modules:
  astro_node_modules:
